//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventosCancun
{
    using System;
    using System.Collections.Generic;
    
    public partial class EtiquetasEvento
    {
        public int ID { get; set; }
        public int IdEvento { get; set; }
        public int IdEtiqueta { get; set; }
    
        public virtual Etiquetas Etiquetas { get; set; }
        public virtual Eventos Eventos { get; set; }
    }
}
