//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventosCancun
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eventos
    {
        public Eventos()
        {
            this.EtiquetasEvento = new HashSet<EtiquetasEvento>();
            this.EventoURLs = new HashSet<EventoURLs>();
        }
    
        public int ID { get; set; }
        public string Titulo { get; set; }
        public string Subtitulo { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public bool EventoVIP { get; set; }
        public string PaginaWeb { get; set; }
        public string NumeroContacto { get; set; }
        public string CorreoContacto { get; set; }
        public string CorreoCliente { get; set; }
        public string NombreCliente { get; set; }
    
        public virtual ICollection<EtiquetasEvento> EtiquetasEvento { get; set; }
        public virtual ICollection<EventoURLs> EventoURLs { get; set; }
    }
}
