//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventosCancun
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EventosCancunEntities : DbContext
    {
        public EventosCancunEntities()
            : base("name=EventosCancunEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Etiquetas> Etiquetas { get; set; }
        public virtual DbSet<EtiquetasEvento> EtiquetasEvento { get; set; }
        public virtual DbSet<EtiquetasUsuario> EtiquetasUsuario { get; set; }
        public virtual DbSet<Eventos> Eventos { get; set; }
        public virtual DbSet<EventoURLs> EventoURLs { get; set; }
        public virtual DbSet<UsuariosMoviles> UsuariosMoviles { get; set; }
    }
}
