//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventosCancun
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuariosMoviles
    {
        public UsuariosMoviles()
        {
            this.EtiquetasUsuario = new HashSet<EtiquetasUsuario>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<bool> Sexo { get; set; }
        public int Estado { get; set; }
        public Nullable<System.Guid> Token { get; set; }
    
        public virtual ICollection<EtiquetasUsuario> EtiquetasUsuario { get; set; }
    }
}
